language: python
dist: Xenial
python: "3.6"

install:
  # Get Migen / LiteX / Cores
  - cd ~/
  - cp $TRAVIS_BUILD_DIR/litex_setup.py .
  - python3 litex_setup.py init install
  # Install the LiteX version being tested.
  - cd $TRAVIS_BUILD_DIR
  - python3 setup.py install

before_script:
  # Get RISC-V toolchain
  - cd ~/
  - python3 litex_setup.py gcc
  - export PATH=$PATH:$PWD/riscv64-unknown-elf-gcc-8.1.0-2019.01.0-x86_64-linux-ubuntu14/bin/

script:
  - cd $TRAVIS_BUILD_DIR
  - python setup.py test
