language: python
python:
  - "3.5"

env:
  global:
    - PATH=$HOME/miniconda/bin:$PATH

before_install:
  # Install Miniconda
  - wget https://raw.githubusercontent.com/m-labs/artiq/master/.travis/get-anaconda.sh
  - chmod +x get-anaconda.sh
  - ./get-anaconda.sh
  - source $HOME/miniconda/bin/activate py35
  - conda install anaconda-client
install:
  # workaround for https://github.com/conda/conda-build/issues/466
  - "mkdir -p /home/travis/miniconda/conda-bld/linux-64"
  - "conda index /home/travis/miniconda/conda-bld/linux-64"
  - "conda build --python 3.5 conda/misoc"
  - "conda install $(conda build --output --python 3.5 conda/misoc)"
script:
  - true

after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then anaconda login --hostname $(hostname) --username $binstar_login --password $binstar_password; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then anaconda upload --user $binstar_login --channel dev --force $HOME/miniconda/conda-bld/noarch/misoc-*.tar.bz2; fi

notifications:
  email: false
  irc:
    channels:
      - chat.freenode.net#m-labs
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
